name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-python-39:
    runs-on: ubuntu-latest
    name: Test Python 3.9
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Debug - List files
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in repository root:"
        find . -maxdepth 1 -type f -name "*.py" | head -10
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx
    
    - name: Run basic tests
      run: |
        python test_basic.py
      timeout-minutes: 5
    
    - name: Run full tests
      run: |
        python test_api.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      timeout-minutes: 10

  test-python-310:
    runs-on: ubuntu-latest
    name: Test Python 3.10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx
    
    - name: Run basic tests
      run: |
        python test_basic.py
      timeout-minutes: 5
    
    - name: Run full tests
      run: |
        python test_api.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      timeout-minutes: 10

  test-python-311:
    runs-on: ubuntu-latest
    name: Test Python 3.11
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx
    
    - name: Run basic tests
      run: |
        python test_basic.py
      timeout-minutes: 5
    
    - name: Run full tests
      run: |
        python test_api.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      timeout-minutes: 10

  docker-build:
    runs-on: ubuntu-latest
    needs: [test-python-39, test-python-310, test-python-311]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and test Docker image
      run: |
        docker build -t fitscore-calculator .
        docker run -d --name test-container -p 8000:8000 fitscore-calculator
        sleep 10
        curl -f http://localhost:8000/health
        docker stop test-container
        docker rm test-container

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to production
      run: |
        echo "Deployment would happen here"
        # Add your deployment steps here
        # Examples:
        # - Deploy to Heroku
        # - Deploy to AWS
        # - Deploy to Google Cloud 
